from Sherlock import *

#print('HELLO')


AnalyseSherlockJson('json/1-Bytes32Lib.json')
AnalyseSherlockJson('json/1-Bytes32Lib425.json')
AnalyseSherlockJson('json/2-NePay.json')
AnalyseSherlockJson('json/3-SafeMathLibExt.json')
AnalyseSherlockJson('json/4-EC.json')
AnalyseSherlockJson('json/5-AirDrop.json')
AnalyseSherlockJson('json/6-EthTranchePricing.json')
AnalyseSherlockJson('json/7-ChickenFarm.json')
AnalyseSherlockJson('json/8-Crowdsale.json')
AnalyseSherlockJson('json/9-lockEtherPay.json')
AnalyseSherlockJson('json/10-BarterCoin.json')
AnalyseSherlockJson('json/11-NeobitTokens.json')
AnalyseSherlockJson('json/12-LightYears.json')
AnalyseSherlockJson('json/13-DonationWallet.json')
AnalyseSherlockJson('json/14-COSHATokenCNY.json')
AnalyseSherlockJson('json/15-RequestBitcoinNodesValidation.json')
AnalyseSherlockJson('json/16-SetherToken.json')
AnalyseSherlockJson('json/17-NVISIONCASH.json')
AnalyseSherlockJson('json/18-GdprCrowdsale.json')
AnalyseSherlockJson('json/19-ExploreCoin.json')
AnalyseSherlockJson('json/20-Anaco_Airdrop.json')
AnalyseSherlockJson('json/21-OneMonthLockup.json')
AnalyseSherlockJson('json/22-BancorMarketMaker.json')

AnalyseSherlockJson('json/23-CAVAsset.json')
AnalyseSherlockJson('json/24-EtherScrolls.json')
AnalyseSherlockJson('json/25-MyAdvancedToken.json')
AnalyseSherlockJson('json/26-AuctusPreSaleDistribution.json')
AnalyseSherlockJson('json/27-CGCGToken.json')
AnalyseSherlockJson('json/28-GodviewChain.json')
AnalyseSherlockJson('json/29-LoopringProtocolImpl.json')
AnalyseSherlockJson('json/30-PixoArenaFounderToken.json')
AnalyseSherlockJson('json/31-KYC.json')
AnalyseSherlockJson('json/32-YeedToken.json')
AnalyseSherlockJson('json/33-EtherGames.json')
AnalyseSherlockJson('json/34-Lottery.json')
AnalyseSherlockJson('json/35-MetabaseCrowdSale.json')
AnalyseSherlockJson('json/36-Tripy.json')
AnalyseSherlockJson('json/37-BarrelAgedFOMO.json')
AnalyseSherlockJson('json/38-MEMESCrowdsale.json')
AnalyseSherlockJson('json/39-PlaakPreSale.json')
AnalyseSherlockJson('json/40-Lottery2.json')

